### ISSUE TITLE
https Version is kinda broken

### ISSUE THREAD

**Issue by kakulukia** [Fruitfulcode/Maintenance#1]
Havnt had time to investigate it futher yet, but the SSL version of the maintenance page is kinda broken.
This is how itshould look like:
http://apflstrdl.de/

But this is the https version of it:
https://apflstrdl.de/

Any ideas?

**Comment by ilyapavlov** [comment]
kakulukia,

If you inspect your source code https://apflstrdl.de/
All path to files goes to http:// instead of https:// that's why you don't see css styles

**Comment by kakulukia** [comment]
and it was referring to other urls .. which is why the problem disapeared since we kinda fixed our domain handling .. thy for looking into it anyways and obviously there still is an issue with the posted domain .. grrrrrr cloning a wordpress DB is kinda weird :(
