### ISSUE TITLE
meta name issues

### ISSUE THREAD

**Issue by kOoLiNuS** [Fruitfulcode/Maintenance#18]
Hello!
I have an issue with the 3.1 release. It duplicates everything I have on the Description field. Even the HTML code I have for getting an email from my visitors.
You can check the bad behaviour on: http://www.chiarapice.it

Also, where can I get the 3.0 release?
Thanks

**Comment by kOoLiNuS** [comment]
I've removed the duplicated text commenting out those 2 lines in the index.php page:

`<!-- <meta name="description" content="<?php echo $description; ?>"/> — REMOVED NICOLA -->`

`<!-- <meta property="og:description" content="<?php echo $description; ?>"/> — REMOVED NICOLA -->`

So that the email link and the font-awesome icons are not doubled on the rendered page…

**Comment by ilyapavlov** [comment]
Thanks for your message. We will check the problem. You can download the previous version here https://downloads.wordpress.org/plugin/maintenance.3.0.zip
